[package]
name = "packing_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#nannou = "0.18.1"
kiss3d = "0.35.0"
packing_lib = { path = "../packing_lib"}
